import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";

const port = Number(process.env.W2_DEMO_PORT ?? 4173);
const root = process.cwd();
const receiptPath = path.join(root, "benchmarks", "runs", "w2", "bug-fix", "run-receipt.json");
const resultsPath = path.join(root, "benchmarks", "results", "results.json");
type AnyRecord = Record<string, any>;
function loadData(): AnyRecord {
  const receipt = existsSync(receiptPath) ? JSON.parse(readFileSync(receiptPath, "utf8")) : null;
  const benchmark = existsSync(resultsPath) ? JSON.parse(readFileSync(resultsPath, "utf8")) : null;
  return { receipt, benchmark };
}
function esc(value: unknown): string { return String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char] ?? char)); }
function render(data: AnyRecord): string {
  const receipt = data.receipt ?? { outcome: "UNPROVEN", task: { title: "No captured run" }, agent: { model: "unknown" }, context: {}, actions: {}, changes: {}, verification: { results: [] }, acceptance: [], evidence: [] };
  const benchmark = data.benchmark ?? { runs: [] };
  const outcome = esc(receipt.outcome);
  const context = JSON.stringify(receipt.context ?? {}, null, 2);
  const trace = JSON.stringify((receipt.evidence ?? []).filter((item: AnyRecord) => item.type === "TOOL_EVIDENCE" || item.type === "ASSERTION_EVIDENCE"), null, 2);
  const diff = JSON.stringify(receipt.changes ?? {}, null, 2);
  const verification = JSON.stringify(receipt.verification ?? {}, null, 2);
  const acceptance = JSON.stringify(receipt.acceptance ?? [], null, 2);
  const benchmarkRows = (benchmark.runs ?? []).map((run: AnyRecord) => `<tr><td>${esc(run.fixture_id)}</td><td>${esc(run.condition)}</td><td><span class="status status-${esc(run.status)}">${esc(run.status)}</span></td><td>${esc(run.external_verification?.status)}</td></tr>`).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>W2 Run Receipt</title><style>
  :root{color-scheme:dark;--bg:#0b0f14;--panel:#121923;--line:#263342;--text:#e7edf4;--muted:#91a0b2;--accent:#55d6be;--warn:#f6c85f;--bad:#ff7b83}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% -10%,#193344 0,#0b0f14 48%);color:var(--text);font:14px/1.5 ui-sans-serif,system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:28px 24px 60px}header{display:flex;justify-content:space-between;gap:20px;align-items:end;border-bottom:1px solid var(--line);padding-bottom:20px}h1{font-size:30px;letter-spacing:-.03em;margin:4px 0}h2{font-size:17px;margin:0 0 10px}.eyebrow{color:var(--accent);font-size:11px;text-transform:uppercase;letter-spacing:.15em;font-weight:700}.muted{color:var(--muted)}.hero{display:grid;grid-template-columns:1fr auto;gap:20px;align-items:center;margin:28px 0}.outcome{font-size:30px;font-weight:800;letter-spacing:.05em}.status{display:inline-flex;border:1px solid currentColor;border-radius:999px;padding:3px 9px;font-size:11px;font-weight:800;letter-spacing:.06em}.status-PASS{color:var(--accent)}.status-FAIL,.status-ERROR{color:var(--bad)}.status-UNPROVEN,.status-ABORTED,.status-INFRASTRUCTURE_FAILURE{color:var(--warn)}.meta{display:flex;gap:18px;flex-wrap:wrap;color:var(--muted)}.meta strong{display:block;color:var(--text);font-weight:600}.panel{background:color-mix(in srgb,var(--panel) 90%,transparent);border:1px solid var(--line);border-radius:14px;padding:18px;margin:14px 0}.nav{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.tab{background:transparent;border:1px solid var(--line);color:var(--muted);border-radius:8px;padding:8px 12px;cursor:pointer}.tab:hover,.tab:focus-visible,.tab[aria-selected=true]{border-color:var(--accent);color:var(--text);outline:2px solid color-mix(in srgb,var(--accent) 55%,transparent);outline-offset:2px}.view{display:none}.view.active{display:block}pre{white-space:pre-wrap;overflow:auto;color:#c9d5e2;background:#0a0d12;border:1px solid var(--line);border-radius:9px;padding:14px;max-height:430px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em}@media(max-width:700px){main{padding:18px 14px}.hero{grid-template-columns:1fr}.outcome{font-size:24px}header{align-items:start;flex-direction:column}}
  </style></head><body><main><header><div><div class="eyebrow">W2 / evidence-first run</div><h1>Run Receipt</h1><div class="muted">Know what the agent saw. Know what it did. Know whether it worked.</div></div><div class="muted">Demo mode · captured data</div></header>
  <section class="hero panel"><div><div class="eyebrow">Did it work?</div><div class="outcome status-${outcome}">${outcome}</div><p>${esc(receipt.task?.title)} — ${esc(receipt.task?.goal)}</p><div class="meta"><span>Run<strong>${esc(receipt.run_id ?? "n/a")}</strong></span><span>Agent<strong>${esc(receipt.agent?.model)}</strong></span><span>Context<strong>${esc(receipt.context?.files_supplied ?? 0)} files</strong></span><span>Actions<strong>${esc(receipt.actions?.tool_calls ?? 0)} tool calls</strong></span></div></div><div><span class="status status-${outcome}">${outcome === "UNPROVEN" ? "Evidence missing" : outcome}</span></div></section>
  <nav class="nav" aria-label="Receipt views"><button class="tab" aria-selected="true" data-view="runs">Runs</button><button class="tab" aria-selected="false" data-view="context">Context</button><button class="tab" aria-selected="false" data-view="trace">Trace</button><button class="tab" aria-selected="false" data-view="diff">Diff</button><button class="tab" aria-selected="false" data-view="verification">Verification</button><button class="tab" aria-selected="false" data-view="acceptance">Acceptance Evidence</button><button class="tab" aria-selected="false" data-view="benchmark">Benchmark</button></nav>
  <section id="runs" class="view active"><div class="panel"><h2>Runs</h2><p class="muted">The receipt is the primary artifact. This demo opens a real captured W2 run; no synthetic PASS is shown.</p><p><span class="status status-${outcome}">${outcome}</span> is the persisted outcome.</p></div></section>
  <section id="context" class="view"><div class="panel"><h2>What the agent saw</h2><pre>${esc(context)}</pre></div></section>
  <section id="trace" class="view"><div class="panel"><h2>What the agent did</h2><pre>${esc(trace)}</pre></div></section>
  <section id="diff" class="view"><div class="panel"><h2>Changed files</h2><pre>${esc(diff)}</pre></div></section>
  <section id="verification" class="view"><div class="panel"><h2>Verification</h2><pre>${esc(verification)}</pre></div></section>
  <section id="acceptance" class="view"><div class="panel"><h2>Acceptance evidence</h2><pre>${esc(acceptance)}</pre></div></section>
  <section id="benchmark" class="view"><div class="panel"><h2>Benchmark evidence</h2><table><thead><tr><th>Fixture</th><th>Condition</th><th>Status</th><th>Verifier</th></tr></thead><tbody>${benchmarkRows || '<tr><td colspan="4">Benchmark unavailable</td></tr>'}</tbody></table></div></section>
  <script>document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(item=>item.setAttribute('aria-selected','false'));document.querySelectorAll('.view').forEach(item=>item.classList.remove('active'));button.setAttribute('aria-selected','true');document.getElementById(button.dataset.view).classList.add('active')}));</script></main></body></html>`;
}
function respond(res: ServerResponse, status: number, body: string, type = "text/html; charset=utf-8"): void { res.writeHead(status, { "content-type": type, "cache-control": "no-store" }); res.end(body); }
function handler(req: IncomingMessage, res: ServerResponse): void { const url = req.url ?? "/"; if (url === "/favicon.ico") return respond(res, 204, "", "image/x-icon"); if (url === "/api/demo") return respond(res, 200, JSON.stringify(loadData()), "application/json"); if (url === "/health") return respond(res, 200, JSON.stringify({ status: "ok", receipt: existsSync(receiptPath), benchmark: existsSync(resultsPath) }), "application/json"); if (url === "/" || url.startsWith("/?")) return respond(res, 200, render(loadData())); respond(res, 404, "Not found", "text/plain; charset=utf-8"); }
if (process.argv.includes("--smoke")) { const html = render(loadData()); const checks = ["Run Receipt", "What the agent saw", "What the agent did", "Did it work?", "Acceptance Evidence", "Benchmark evidence", "UNPROVEN"]; const missing = checks.filter((check) => !html.includes(check)); if (missing.length) { console.error(`UI smoke failed: ${missing.join(", ")}`); process.exit(1); } console.log("UI smoke: PASS"); } else { createServer(handler).listen(port, "127.0.0.1", () => console.log(`W2 demo running at http://127.0.0.1:${port}`)); }
